### ISSUE TITLE
스프린트4 쿠폰 기능 1차 QA 수정사항 반영

### ISSUE THREAD

**Issue by minseo-hong** [Let-s-intern/lets-intern-client#436]
## Todo
- [x] 쿠폰 등록 제출하기 안되는 문제
- [x] 쿠폰 등록 후 화살표로 모달 닫은 후 다시 열면 쿠폰 번호 없이 할인만 되는 문제
- [x] 필독사항 항목에서 모달이 닫히지 않는 오류
- [x] 프로그램 모바일 신청 컴포넌트 UI 반응형 수정
- [x] 프로그램 신청 다음 단계 넘어갈 시 스크롤 최상단으로 가도록 수정
- [x] 쿠폰 제출 예외처리 관련 오류 워딩 수정
